[2015-10-30 05:21:04,572: WARNING/MainProcess] worker@omega008 ready.
[2015-10-30 07:18:19,014: ERROR/Worker-26] nidaba.segmentation.tesseract[de2c5657-b6fb-43b7-93f8-f82e28159cb6]: Tesseract killed by signal: 11
[2015-10-30 07:18:21,344: ERROR/MainProcess] Task nidaba.segmentation.tesseract[de2c5657-b6fb-43b7-93f8-f82e28159cb6] raised unexpected: NidabaTesseractException(u'Tesseract killed by signal: 11',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/tesseract.py", line 251, in segmentation_tesseract
    raise NidabaTesseractException('Tesseract killed by signal: {0}'.format(os.WTERMSIG(status)))
NidabaTesseractException: Tesseract killed by signal: 11
[2015-10-30 08:00:37,077: WARNING/Worker-22] /cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py:91: RuntimeWarning: invalid value encountered in true_divide
  temp = temp*1.0/np.amax(temp)
[2015-10-30 08:00:37,085: WARNING/Worker-22] /cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py:48: RuntimeWarning: invalid value encountered in true_divide
  line = line * 1.0/np.amax(line)
[2015-10-30 08:00:37,159: ERROR/Worker-22] nidaba.ocr.kraken[5a0e3994-87e7-4ebb-9d6d-def8b1eb5608]: 
[2015-10-30 08:00:40,718: ERROR/MainProcess] Task nidaba.ocr.kraken[5a0e3994-87e7-4ebb-9d6d-def8b1eb5608] raised unexpected: AssertionError()
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 155, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 134, in rpred
    pred = network.predictString(line)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 281, in predictString
    cs = self.predictSequence(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 273, in predictSequence
    self.outputs = np.array(self.lstm.forward(xs))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 229, in forward
    xs = net.forward(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 244, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 216, in forward
    assert not np.isnan(self.output[:n]).any()
AssertionError
[2015-10-30 09:03:49,151: ERROR/Worker-17] nidaba.ocr.kraken[2f61b89f-2669-4fb5-9c2e-a5fc42492d8e]: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:03:52,394: ERROR/MainProcess] Task nidaba.ocr.kraken[2f61b89f-2669-4fb5-9c2e-a5fc42492d8e] raised unexpected: IndexError('index 5000 is out of bounds for axis 0 with size 5000',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 155, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 134, in rpred
    pred = network.predictString(line)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 281, in predictString
    cs = self.predictSequence(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 273, in predictSequence
    self.outputs = np.array(self.lstm.forward(xs))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 229, in forward
    xs = net.forward(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 244, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 196, in forward
    self.source[t,0] = 1
IndexError: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:17:16,493: WARNING/Worker-31] /cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py:91: RuntimeWarning: invalid value encountered in true_divide
  temp = temp*1.0/np.amax(temp)
[2015-10-30 09:20:56,778: ERROR/Worker-26] nidaba.ocr.kraken[96ee6043-fefd-4325-b593-833d52067a1f]: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:20:59,599: ERROR/MainProcess] Task nidaba.ocr.kraken[96ee6043-fefd-4325-b593-833d52067a1f] raised unexpected: IndexError('index 5000 is out of bounds for axis 0 with size 5000',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 155, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 134, in rpred
    pred = network.predictString(line)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 281, in predictString
    cs = self.predictSequence(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 273, in predictSequence
    self.outputs = np.array(self.lstm.forward(xs))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 229, in forward
    xs = net.forward(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 244, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 196, in forward
    self.source[t,0] = 1
IndexError: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:24:37,720: ERROR/Worker-17] nidaba.ocr.kraken[e5a2a380-9ba0-40b2-850e-e12270cf18c3]: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:24:40,804: ERROR/MainProcess] Task nidaba.ocr.kraken[e5a2a380-9ba0-40b2-850e-e12270cf18c3] raised unexpected: IndexError('index 5000 is out of bounds for axis 0 with size 5000',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 155, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 134, in rpred
    pred = network.predictString(line)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 281, in predictString
    cs = self.predictSequence(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 273, in predictSequence
    self.outputs = np.array(self.lstm.forward(xs))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 229, in forward
    xs = net.forward(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 244, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 196, in forward
    self.source[t,0] = 1
IndexError: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:26:12,084: ERROR/Worker-28] nidaba.ocr.kraken[61406071-bea8-47a4-bcf4-5c5fbb93bb0d]: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:26:14,640: ERROR/MainProcess] Task nidaba.ocr.kraken[61406071-bea8-47a4-bcf4-5c5fbb93bb0d] raised unexpected: IndexError('index 5000 is out of bounds for axis 0 with size 5000',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 155, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 134, in rpred
    pred = network.predictString(line)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 281, in predictString
    cs = self.predictSequence(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 273, in predictSequence
    self.outputs = np.array(self.lstm.forward(xs))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 229, in forward
    xs = net.forward(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 244, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 196, in forward
    self.source[t,0] = 1
IndexError: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:30:16,693: ERROR/Worker-16] nidaba.ocr.kraken[8325e040-d2b0-4010-90ba-d6129fa166c9]: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:30:28,465: ERROR/Worker-33] nidaba.ocr.kraken[70027b8d-9da5-4c22-87f2-8ae541b6fa2b]: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:30:28,976: ERROR/MainProcess] Task nidaba.ocr.kraken[8325e040-d2b0-4010-90ba-d6129fa166c9] raised unexpected: IndexError('index 5000 is out of bounds for axis 0 with size 5000',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 155, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 134, in rpred
    pred = network.predictString(line)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 281, in predictString
    cs = self.predictSequence(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 273, in predictSequence
    self.outputs = np.array(self.lstm.forward(xs))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 229, in forward
    xs = net.forward(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 244, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 196, in forward
    self.source[t,0] = 1
IndexError: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:31:03,591: ERROR/MainProcess] Task nidaba.ocr.kraken[70027b8d-9da5-4c22-87f2-8ae541b6fa2b] raised unexpected: IndexError('index 5000 is out of bounds for axis 0 with size 5000',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 155, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 134, in rpred
    pred = network.predictString(line)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 281, in predictString
    cs = self.predictSequence(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 273, in predictSequence
    self.outputs = np.array(self.lstm.forward(xs))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 229, in forward
    xs = net.forward(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 244, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 196, in forward
    self.source[t,0] = 1
IndexError: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:34:11,221: ERROR/Worker-38] nidaba.ocr.kraken[60604144-4aea-494e-a4d8-d287debf92c5]: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:34:14,059: ERROR/MainProcess] Task nidaba.ocr.kraken[60604144-4aea-494e-a4d8-d287debf92c5] raised unexpected: IndexError('index 5000 is out of bounds for axis 0 with size 5000',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 155, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 134, in rpred
    pred = network.predictString(line)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 281, in predictString
    cs = self.predictSequence(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 273, in predictSequence
    self.outputs = np.array(self.lstm.forward(xs))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 229, in forward
    xs = net.forward(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 244, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 196, in forward
    self.source[t,0] = 1
IndexError: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:36:31,235: ERROR/Worker-6] nidaba.ocr.kraken[b90fc382-eaa8-4075-ab5c-28f08fd7253a]: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:36:33,626: ERROR/MainProcess] Task nidaba.ocr.kraken[b90fc382-eaa8-4075-ab5c-28f08fd7253a] raised unexpected: IndexError('index 5000 is out of bounds for axis 0 with size 5000',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 155, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 134, in rpred
    pred = network.predictString(line)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 281, in predictString
    cs = self.predictSequence(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 273, in predictSequence
    self.outputs = np.array(self.lstm.forward(xs))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 229, in forward
    xs = net.forward(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 244, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 196, in forward
    self.source[t,0] = 1
IndexError: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:38:22,058: ERROR/Worker-11] nidaba.ocr.kraken[573dcae8-9897-44d8-ae7d-fdd1b376b72e]: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:38:29,160: ERROR/MainProcess] Task nidaba.ocr.kraken[573dcae8-9897-44d8-ae7d-fdd1b376b72e] raised unexpected: IndexError('index 5000 is out of bounds for axis 0 with size 5000',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 155, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 134, in rpred
    pred = network.predictString(line)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 281, in predictString
    cs = self.predictSequence(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 273, in predictSequence
    self.outputs = np.array(self.lstm.forward(xs))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 229, in forward
    xs = net.forward(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 244, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 196, in forward
    self.source[t,0] = 1
IndexError: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:38:37,845: ERROR/Worker-1] nidaba.ocr.kraken[99127ba3-20a0-4022-a4d2-fa5bfe797f2b]: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 09:38:39,780: ERROR/MainProcess] Task nidaba.ocr.kraken[99127ba3-20a0-4022-a4d2-fa5bfe797f2b] raised unexpected: IndexError('index 5000 is out of bounds for axis 0 with size 5000',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 155, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 134, in rpred
    pred = network.predictString(line)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 281, in predictString
    cs = self.predictSequence(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 273, in predictSequence
    self.outputs = np.array(self.lstm.forward(xs))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 229, in forward
    xs = net.forward(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 244, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 196, in forward
    self.source[t,0] = 1
IndexError: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 11:09:15,211: ERROR/Worker-16] nidaba.ocr.kraken[9faaed1d-78f3-47b9-9108-48dcab4dcc68]: index 5000 is out of bounds for axis 0 with size 5000
[2015-10-30 11:09:15,920: ERROR/MainProcess] Task nidaba.ocr.kraken[9faaed1d-78f3-47b9-9108-48dcab4dcc68] raised unexpected: IndexError('index 5000 is out of bounds for axis 0 with size 5000',)
Traceback (most recent call last):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/tasks/helper.py", line 89, in __call__
    ret = super(NidabaTask, self).__call__(*args, **nkwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/nidaba/plugins/kraken.py", line 155, in ocr_kraken
    for rec in rpred.rpred(rnn, img, [(int(x[0]), int(x[1]), int(x[2]), int(x[3])) for x in lines]):
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/rpred.py", line 134, in rpred
    pred = network.predictString(line)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 281, in predictString
    cs = self.predictSequence(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 273, in predictSequence
    self.outputs = np.array(self.lstm.forward(xs))
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 229, in forward
    xs = net.forward(xs)
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 244, in forward
    outputs = [net.forward(xs) for net in self.nets]
  File "/cluster/home/mmunso01/envs/nidaba/lib/python2.7/site-packages/kraken/lib/lstm.py", line 196, in forward
    self.source[t,0] = 1
IndexError: index 5000 is out of bounds for axis 0 with size 5000
